# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c85c843270916125ee996e7aa4023c2"
name = "mustang-b2b-functions"
application_url = "https://b2b-free-shipping-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "write_delivery_customizations,read_delivery_customizations"

[auth]
redirect_urls = [ "https://b2b-free-shipping-production.up.railway.app/auth/callback" ]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
