api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "b2b-free-shipping"
type = "function"
uid = "dd26ee84-7c69-4f27-a0be-a2d65b8ff7cea59462aa"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
