api_version = "2026-07"
uid = "487243ee-7974-e4ef-ea1e-c4dc66a5555f5087fbdd"

[[extensions]]
name = "B2B Free Shipping Config"
handle = "b2b-free-shipping-config"
type = "ui_extension"
description = "Delivery customization activation page for B2B Free Shipping"

  [[extensions.targeting]]
  target = "admin.delivery-customization.action.render"
  module = "./src/index.tsx"

  [extensions.build]
  command = "node ./build.js"
  path = "dist"
